# Generated by Django 5.0.2 on 2024-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authtor_name',
            field=models.CharField(default='Authtor', max_length=255),
            preserve_default=False,
        ),
    ]
